
package ywx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebApp", targetNamespace = "http://ywx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebApp {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayhi", targetNamespace = "http://ywx/", className = "ywx.Sayhi")
    @ResponseWrapper(localName = "sayhiResponse", targetNamespace = "http://ywx/", className = "ywx.SayhiResponse")
    @Action(input = "http://ywx/WebApp/sayhiRequest", output = "http://ywx/WebApp/sayhiResponse")
    public String sayhi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
